[package]
name = "shadow-rs"
version = "0.15.0"
authors = ["baoyachi <liaoymxsdl@gmail.com>"]
edition = "2021"
description = "A build-time information stored in your rust project"
keywords = ["cargo", "build-script", "build", "shadow", "compile"]
readme = "README.md"
categories = ["development-tools", "development-tools::build-utils"]
repository = "https://github.com/baoyachi/shadow-rs"
documentation = "https://docs.rs/shadow-rs"
homepage = "https://github.com/baoyachi/shadow-rs"
license = "MIT AND Apache-2.0"
exclude = ["shadow-rs.png", "build_module.png"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[package.metadata.docs.rs]
all-features = true

[dependencies]
is_debug = "1.0.1"
const_format = "0.2.22"
time = { version = "0.3.11", features = ["formatting", "local-offset", "parsing"] }
tzdb = { version = "0.2.7", default-features = false, features = ["local"] }

#! Optional Dependencies:

## Use `libgit2` as a backend for git operations
git2 = { version = "0.14.2", default-features = false, optional = true }

document-features = { version = "0.2", optional = true }

[features]
default = ["git2"]

[workspace]
members = ["example_shadow", "example_shadow_hook"]
